version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgresql
            port: 5432
            user: drake
            password: 910330
            migrations: true

  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: 'drake'
      POSTGRES_PASSWORD: "910330"
      POSTGRES_DB: "csvdb"
    ports: 
      - "5432:5432"

  server:
    image: server:latest
    build: ./
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - "prisma"
 
