version: '3'
services:
  postgres:
     image: postgres
     container_name: postgres
     restart: always
     ports: 
      - 5432:5432
     environment: 
      POSTGRES_USER: 'drake'
      POSTGRES_PASSWORD: "910330"
      POSTGRES_DB: "csvdb"
  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: ./nginx/
    ports:
      - "80:80"

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: "drake"
            password: "910330"
            migrations: true
            database: "csvdb"

  api:
    image: server:latest
    build: ./server/
    env_file: ./server/.env
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - default   

  client:
    image: client:latest
    build: ./client/
    env_file: ./client/.env
    ports:
      - "5000:5000"
    restart: always
    networks:
      - default 
 
